AllCops:
  TargetRubyVersion: 2.6 # TODO ADJUST RUBY VERSION
  DisabledByDefault: true

  Exclude:
    - '**/tmp/**/*'
    - '**/vendor/**/*'
    - '**/node_modules/**/*'
    - 'bin/bundle'

Layout/LineLength:
  Max: 130

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/HashSyntax:
  Enabled: true
  EnforcedStyle: ruby19_no_mixed_keys
